### ISSUE TITLE
Disconnecting with error 1002 when trying to register in Android App

### ISSUE THREAD

**Issue by joaquin03** [flutter-webrtc/dart-sip-ua#129]
Hi!

 I got the registration and videocall working perfectly via an Asterisk webRTC server with the chrome installation. 

Now I installed it in Android, in the emulator when registering it connects and instantly disconnects with error 1002. 

Any help would be awesome,

Thanks!

**Comment by cloudwebrtc** [comment]
I think you can try this version, https://github.com/flutter-webrtc/dart-sip-ua/commit/cd1e37a79e868c5bfef7ea2c439c2dbc788930f9,

On the old version of FreeSwitch, because of the problem caused by the case sensitivity of the WebSocket Upgrade Header, we got the normal registration after changing to the mandatory case (dart-sdk will convert all HTTP headers to lower case by default), so maybe on asterisk, The same problem exists.
