### ISSUE TITLE
Does the library support native SIP?

### ISSUE THREAD

**Issue by morfair** [flutter-webrtc/dart-sip-ua#237]
Does the library support native SIP over UDP or only WebRTC?

**Comment by cloudwebrtc** [comment]
Using WebSocket + webrtc is currently the most reasonable combination. If UDP transmits signaling, you have to return the webrtc stack to normal UDP/RTP, because the SDP length of webrtc will exceed 1500, and INVITE signaling cannot be transmitted via UDP.

The technical level of your issue is feasible, which will require the development of a customized version, and the development cost is higher.

**Comment by morfair** [comment]
Understood, normal SIP/RTP over UDP is not supported now.
Thanks you for answer.
