### ISSUE TITLE
I want to know if the other user accepts or decline and implement call recording.

### ISSUE THREAD

**Issue by Hercules2013** [flutter-webrtc/dart-sip-ua#388]
Hello, @cloudwebrtc 
I am developing sip call app using sip_ua package.
Even if the receiver accepts or reject, the state becomes CallStateEnum.ACCEPTED and CallStateEnum.CONFIRMED.
so I can't know that receiver accepts or reject call.
And also I want to record call.
I have two media streams(local media stream and remote media stream) and implemented recording mixed audio stream in web using MediaRecorder API.
I want to do same function in windows and macos.
In mobile case, we can use flutter_sound package.
In desktop case, what can I use?

**Comment by kansshsj** [comment]
I think the call got terminated if the receiver reject but it seems like the connection is alive for 6 seconds because it plays error sound that user has rejected the call.
And to talk about media recording, there is no package that supports your purpose.
As you know, the disadvantage of flutter is the limited packages or libraries.
I think you can develop your own recording package using platform-specific API.
Thanks for your time.

**Comment by Hercules2013** [comment]
Thanks, @kansshsj

**Comment by Hercules2013** [comment]
@kansshsj answered.
